In [3]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.datasets import mnist
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [4]:
print(train_images.shape)
print(train_labels)
print(test_images.shape)
print(test_labels)


(60000, 28, 28)
[5 0 4 ... 5 6 8]
(10000, 28, 28)
[7 2 1 ... 4 5 6]


In [5]:
from tensorflow import keras
from tensorflow.keras import layers
model = keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dropout(0.2),

    layers.Dense(10, activation="softmax")
])

In [6]:
model.compile(optimizer="rmsprop",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

In [7]:
train_images = train_images.reshape((60000, 28 *28 ))

train_images = train_images.astype("float32") / 255
test_images = test_images.reshape((10000, 28 *28))
test_images = test_images.astype("float32") / 255


In [8]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5


2024-04-22 23:54:53.275978: W external/local_tsl/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 188160000 exceeds 10% of free system memory.


469/469 ━━━━━━━━━━━━━━━━━━━━ 10s 15ms/step - accuracy: 0.8642 - loss: 0.4668
Epoch 2/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 6s 12ms/step - accuracy: 0.9614 - loss: 0.1306
Epoch 3/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 10ms/step - accuracy: 0.9740 - loss: 0.0837
Epoch 4/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 5s 11ms/step - accuracy: 0.9814 - loss: 0.0611
Epoch 5/5
469/469 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - accuracy: 0.9839 - loss: 0.0504


In [9]:
test_digits = test_images[0:10]
predictions = model.predict(test_digits)
predictions[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step


array([1.5714607e-08, 2.6087296e-10, 3.9744596e-06, 1.3151364e-06,
       1.1935834e-12, 1.1681106e-09, 3.3947573e-13, 9.9999470e-01,
       1.2587221e-08, 4.0564679e-08], dtype=float32)